### ISSUE TITLE
MIcro PArts To-Do list

### ISSUE THREAD

**Issue by Elix-x** [AEModernMCPort/Applied-Energistics-3-ReOver#2]
## Branch [codename:mipa](https://github.com/AEModernMCPort/Applied-Energistics-3-ReOver/tree/codename-mipa).

This is a list of things that have to be done on the MIPA branch, beyond ones marked in code with `//TODO` or `//FIXME`.
Feel free to discuss them here, or in our discord, suggest changes or possible implementations. Doing them yourself and PRing is not only possible, but also very _very_ appreciated.

- [ ] Make parts playable in survival. And by that i mean, right now parts don't drop anything, don't have breaking duration, etc...
- [x] Implement modular-ly rendered part models (to allow connected textures for cables and multipart formations). This is something that requires very deep thinking and design choices.
As a reminder, parts are 50% driven by code and 50% by assets/data. That is, both the physics of part (occupied volume and collisions) and how it looks are driven by wavefront models in assets. AKA, part meshes are loaded server side. Thus, we do _not_ have access to any existing MC/Forge model framework (json blockstates).
The parts system was designed with 1-part-1-mesh model in mind (similar to elimination of metadata in 1.13), meaning that parts can't have any properties that physically affect their mesh (not something that will happen to blocks in 1.13).
Because of all factors described previously, the design must be chose thought-fully and then implemented accordingly, to allow connected cable textures, while not creating what-i-see - what-i-touch discrepancies, and be modifiable together with mesh.
- [ ] Implement connected faces culling for parts (like glass cables). Now, same design choices are required as above. Possibly, this could be merged with one above and the implementation of modular-ly rendered models could also satisfy this entry.
- [ ] Ray tracing through meshes. Once ray was confirmed to hit a voxel with a part, ray trace it through part's mesh, to further decrease what-i-see - what-i-select discrepancies.
- [ ] Fix voxelization algorithm implementation artifacts. The abstract algorithm in itself does work correctly (checked by time and in other languages). But my java implementation of it occasionally burps artifacts for some rare faces.
- [ ] Fix item rendering. Most of parts items are simply outside of the screen. In all cases.
- [ ] Explosion handling? Maybe? Maybe not? But we should at least increase parts container's default explosion resistance... probably.
- [ ] Implement C&B and MCMP support.

**Comment by Elix-x** [comment]
- [ ] Implement C&B and MCMP support.

**Comment by StrayCargo** [comment]
suggest moving this to projects so we can keep the issues cleaned for bugs and critical issues
